"""Add interview tables

Revision ID: 117e78a375be
Revises: 
Create Date: 2025-12-28 17:03:52.222032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '117e78a375be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('interview_type', sa.Enum('COMPANY_SPECIFIC', 'CUSTOM_TOPIC', name='interviewtype'), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('custom_topics', sa.JSON(), nullable=True),
    sa.Column('total_rounds', sa.Integer(), nullable=True),
    sa.Column('completed_rounds', sa.Integer(), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('pass_fail_status', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'PAUSED', 'COMPLETED', 'ABANDONED', name='interviewstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.String(), nullable=False),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('communication_score', sa.Float(), nullable=True),
    sa.Column('problem_solving_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('suggested_topics', sa.JSON(), nullable=True),
    sa.Column('next_interview_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id')
    )
    op.create_table('interview_recordings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.String(), nullable=False),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('transcript_url', sa.String(), nullable=True),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('recording_duration', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('video_format', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id')
    )
    op.create_table('interview_rounds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('interview_id', sa.String(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('round_type', sa.Enum('TECHNICAL', 'HR', 'COMMUNICATION', name='roundtype'), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('LOCKED', 'UNLOCKED', 'IN_PROGRESS', 'PASSED', 'FAILED', name='roundstatus'), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('pass_threshold', sa.Float(), nullable=True),
    sa.Column('pass_status', sa.Boolean(), nullable=True),
    sa.Column('feedback_summary', sa.Text(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.String(), nullable=False),
    sa.Column('round_id', sa.String(), nullable=False),
    sa.Column('speaker', sa.String(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('question_category', sa.String(), nullable=True),
    sa.Column('expected_answer_points', sa.JSON(), nullable=True),
    sa.Column('answer_score', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('confidence_detected', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['interview_rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_conversations')
    op.drop_table('interview_rounds')
    op.drop_table('interview_recordings')
    op.drop_table('interview_evaluations')
    op.drop_table('interviews')
    # ### end Alembic commands ###
