"""Add roadmap tables

Revision ID: 982e701a8b20
Revises: 42d37f20e0f2
Create Date: 2025-12-31 11:57:25.459532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '982e701a8b20'
down_revision: Union[str, None] = '42d37f20e0f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmaps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('target_role', sa.String(length=255), nullable=False),
    sa.Column('target_timeline_weeks', sa.Integer(), nullable=True),
    sa.Column('roadmap_data', sa.JSON(), nullable=True),
    sa.Column('diagram_svg_url', sa.String(length=1000), nullable=True),
    sa.Column('diagram_png_url', sa.String(length=1000), nullable=True),
    sa.Column('diagram_text', sa.Text(), nullable=True),
    sa.Column('overall_progress_percent', sa.Float(), nullable=True),
    sa.Column('current_phase', sa.Enum('FOUNDATION', 'INTERMEDIATE', 'ADVANCED', 'SPECIALIZATION', name='roadmapphase'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmap_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('roadmap_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('phase', sa.Enum('FOUNDATION', 'INTERMEDIATE', 'ADVANCED', 'SPECIALIZATION', name='roadmapphase'), nullable=False),
    sa.Column('skill_name', sa.String(length=255), nullable=False),
    sa.Column('task_title', sa.String(length=500), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=True),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED', name='taskstatus'), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('google_calendar_event_id', sa.String(length=255), nullable=True),
    sa.Column('calendar_synced', sa.Boolean(), nullable=True),
    sa.Column('resources', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roadmap_tasks')
    op.drop_table('roadmaps')
    # ### end Alembic commands ###
