"""Added Journal model

Revision ID: b782ff445a6d
Revises: aa5fc8bfc732
Create Date: 2025-12-29 01:20:30.251613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b782ff445a6d'
down_revision: Union[str, None] = 'aa5fc8bfc732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
